### ISSUE TITLE
Deivu can you please add spotify support

### ISSUE THREAD

**Issue by vkamsingh** [Deivu/Shoukaku#106]
hello sir,
it was to hard get metadata of track and play it through ytsearch. please deivu add spotify support through plugin please please please............ : (

your thanks,
unhappy shoukaku user with lots of sadness

**Comment by Deivu** [comment]
Unfortunately, Shoukaku works 1:1 with lavalink api, and only what the lavalink api provide is what we would provide. You have the option to modify the Rest inside shoukaku just read the readme.md but keep it mind that I wont be providing any support on any custom rest client
