### ISSUE TITLE
Questions about v4 

### ISSUE THREAD

**Issue by flav28** [Deivu/Shoukaku#130]
player.filters.volume is possibly 'undefined'
This is normal in master ?

**Comment by flav28** [comment]
Connection.resendServerUpdate() removed
maybe re add it

**Comment by flav28** [comment]
The previous system was good for reconnecting nodes
![image](https://user-images.githubusercontent.com/48295189/214638307-b7ae2833-729b-4d35-ab75-8eddfde9bea6.png)

**Comment by Deivu** [comment]
> player.filters.volume is possibly 'undefined' This is normal in master ?

Intended behavior for now, since volume can be based on implementation guidelines

**Comment by Deivu** [comment]
> Connection.resendServerUpdate() removed maybe re add it

Removed, you can provide the data via setServerUpdate() yourself
