### ISSUE TITLE
Error: 404

### ISSUE THREAD

**Issue by Fyphen1223** [Deivu/Shoukaku#161]
Unexpected server response: 404

I'm running v4 Lavalink, and wrote exact certification, but code says it cannot connect to lavalink.

**Comment by seammd124** [comment]
> Unexpected server response: 404
> 
> I'm running v4 Lavalink, and wrote exact certification, but code says it cannot connect to lavalink.

Update shoukaku with "npm i github:Deivu/Shoukaku" (Make sure u have git installed in ur server)

**Comment by Fyphen1223** [comment]
Ah shoukaku package on npm is still v3?

**Comment by Fyphen1223** [comment]
Oh no I think that's right sorry guys

**Comment by Deivu** [comment]
I lock the npm version with the same version what lavalink considers as stable, until lavalink says v4 api is stable, shoukaku's v4 support will not be released in the stable channel

**Comment by Fyphen1223** [comment]
I see, thank you so much all guys
