### ISSUE TITLE
Player ends playing song after around 15 seconds or so

### ISSUE THREAD

**Issue by Reishimanfr** [Deivu/Shoukaku#163]
initializing shoukaku with
import { Shoukaku, Connectors } from 'shoukaku';

`const Nodes = [
  {
    name: 'localhost',
    url: 'localhost:2333',
    auth: 'MyPassword',
  },
];

const shoukaku = new Shoukaku(new Connectors.DiscordJS(client), Nodes);
`

all worked fine, until the bot randomly decided to leave the voice channel
after printing out the `player.reason` I got `FINISHED`, even though the song wasn't even halfway through

Lavalink: v3.7.7
Shoukaku: v3.4.0
Node.js: v18.17.0

**Comment by Deivu** [comment]
Did you already ask around Lavalink? This is most likely a Lavalink/Lavaplayer issue

**Comment by AADI0009** [comment]
> initializing shoukaku with import { Shoukaku, Connectors } from 'shoukaku';
> 
> `const Nodes = [ { name: 'localhost', url: 'localhost:2333', auth: 'MyPassword', }, ];
> 
> const shoukaku = new Shoukaku(new Connectors.DiscordJS(client), Nodes); `
> 
> all worked fine, until the bot randomly decided to leave the voice channel after printing out the `player.reason` I got `FINISHED`, even though the song wasn't even halfway through
> 
> Lavalink: v3.7.7 Shoukaku: v3.4.0 Node.js: v18.17.0


Lavalink Support Server: https://discord.gg/s9PZY5x8Gg

**Comment by Reishimanfr** [comment]
> Did you already ask around Lavalink? This is most likely a Lavalink/Lavaplayer issue

not yet, I'll try asking them
thanks!
