### ISSUE TITLE
End is being emitted twice.

### ISSUE THREAD

**Issue by Milo123459** [Deivu/Shoukaku#22]
The code can be found at [this repo](https://github.com/Milo123459/Spencer) - end is being emitted twice.

**Comment by Deivu** [comment]
Log whatever comes out on the end has a parameter which is data, log what data entails

**Comment by Milo123459** [comment]
@Deivu I logged it and they are both identical. Same track id, etc.

**Comment by Deivu** [comment]
I wanna know the raw object itself

**Comment by Milo123459** [comment]
Oh, please wait

**Comment by Milo123459** [comment]
Also, my queue system is broken and I can't figure it out. Not related but well, the end event has something to do with it because it keeps emitting twice.

**Comment by Milo123459** [comment]
{
  op: 'event',
  reason: 'FINISHED',
  type: 'TrackEndEvent',
  track: 'QAAAewIAFkFsbCBvdmVyIGluIDEwIHNlY29uZHMAC0lhbiBSdXNodG9uAAAAAAAAJxAAC3JVV3hTRXdjdEZVAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9clVXeFNFd2N0RlUAB3lvdXR1YmUAAAAAAAAm/A==',
  guildId: '784470505607528448'
}
@Deivu

**Comment by Deivu** [comment]
> {
> op: 'event',
> reason: 'FINISHED',
> type: 'TrackEndEvent',
> track: 'QAAAewIAFkFsbCBvdmVyIGluIDEwIHNlY29uZHMAC0lhbiBSdXNodG9uAAAAAAAAJxAAC3JVV3hTRXdjdEZVAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9clVXeFNFd2N0RlUAB3lvdXR1YmUAAAAAAAAm/A==',
> guildId: '784470505607528448'
> }
> @Deivu

is this the same for the 2nd emit? I wanna see both the first emitted and second emitted

**Comment by Milo123459** [comment]
Exactly the same

**Comment by Deivu** [comment]
Do this happen all the time or not all the time, or there are just instances that it happens or not?

**Comment by Milo123459** [comment]
All the time.

**Comment by Deivu** [comment]
attach a debug listener on your Shoukaku class, params is `name, data` where in the data is the raw output from LL ws, this way we can confirm whether it's Shoukaku or it's LLs doing on this end emitting issue

**Comment by Milo123459** [comment]
Will do.

**Comment by Milo123459** [comment]
- it has stopped happening now. 
BTW, how can I check how long a song has been playing, this is for a now playing command.

**Comment by Deivu** [comment]
Player has a time property, refer to docs for info about that property. You can re-open the issue if this happens again.
