### ISSUE TITLE
any support server for this project??

### ISSUE THREAD

**Issue by kakarot-dev** [Deivu/Shoukaku#35]
![image](https://user-images.githubusercontent.com/76399483/113472525-84860600-9481-11eb-8e15-f475f85ce0a0.png)
this err has been happening when i was using the 1.6.4 version but when i jumped tp 1.5.2 it works perfectly

**Comment by Deivu** [comment]
What Lavalink build are you on, Readme states 1.6.x is for dev Lavalink

**Comment by kakarot-dev** [comment]
Uhh the normal lavalink that everyone uses

**Comment by Deivu** [comment]
Then you are limited to 1.5.x versions of Shoukaku if you aren't on Dev-Branch, Luckily its easy to move to Dev-branch, or just stay with 1.5.x if you intend to keep the normal lavalink aka the master branch lavalink

**Comment by kakarot-dev** [comment]
coolsie btw is there any support discord server so that I can be pinged when 1.6 is compatible with normal lavalink??

**Comment by Deivu** [comment]
It's on other links on readme, you should see support hyperlinked there

**Comment by AliasPedroKarim** [comment]
I have a question, maybe stupid but can't you put your development version on a new branch first?

Instead of breaking your main project with development code!

sorry my english is aproximative ^^'

**Comment by Deivu** [comment]
@AliasPedroKarim 
The master branch isn't necessarily broken, it just adheres to Lavalink's-Next version which removes Num-Shards, thats why if you aren't on Dev Lavalink Branch, aka you are on normal Lavalink, you **should not install 1.6.x** which I clarified on readme.

**Comment by kakarot-dev** [comment]
oki
