### ISSUE TITLE
"PlayerStart" and "playerEnd" event on the client

### ISSUE THREAD

**Issue by kaname-png** [Deivu/Shoukaku#38]
It would be nice to have an event in the client called `playerStart` and `playerEnd`, and to be executed every time a guild player starts or ended.

I say this idea in order to better manage the control of players from one place.

## Example:
```ts
const client = new Shoukaku(options);
client.on("playerStart", (guildId, player) => console.log(guildId, player));

client.on("playerEnd", (guildId, player) => console.log(guildId, player));
```

**Comment by Deivu** [comment]
What kind of management

**Comment by kaname-png** [comment]
## For example:

1. Better queue control to not rely on the `.getPlayer()` method and avoid having many active listeners in different commands.
2. Send notification messages in a simpler way when the music player stops or starts.
3. The most important thing is to be able to do everything from one place and not from several commands.

**Comment by Deivu** [comment]
Possible to be considered on `next` but definitely will not ship in current v1, though I'm not sure how you are not being able to do everything in one place, are you not extending, or making a queue system around the player?

**Comment by kaname-png** [comment]
When I say in one place I mean to manage a queue system for example from a service class, and not to depend on any command.

Sometimes I get an error that says Shoukaku reached max listeners and things like that, that's why I give that idea. That happens by having listeners in commands.

**Comment by Deivu** [comment]
> When I say in one place I mean to manage a queue system for example from a service class, and not to depend on any command.
> 
> Sometimes I get an error that says Shoukaku reached max listeners and things like that, that's why I give that idea. That happens by having listeners in commands.

I usually just store shoukaku player as a property on my own player, then attach listeners on the constructor or have a specific init method that would only be executed once, so you wont re-add any listeners once added

**Comment by kaname-png** [comment]
Do you have any examples of how to implement that in that way you mention?

**Comment by Deivu** [comment]
```js
// create a play function that accepts an existing player
async play(player) {
  const song = await player.voiceConnection.node.resolve('something');
  await player.playTrack(song);
}
// create a player variable, where in we will attach listeners on it once only
const player = await node.joinVoiceChannel();
// use the play function to play your queue, instead of attaching listeners per play function
player.on('end', () => play(player));
// execute play for the first time
play();

**Comment by kaname-png** [comment]
Yes I do, but there are times when I get the error I mentioned even when using a method like that.

**Comment by Deivu** [comment]
> Yes I do, but there are times when I get the error I mentioned even when using a method like that.

Are you sure you are not re attaching listeners? the ideal scenario is to ensure you only attach the listeners at once

**Comment by kaname-png** [comment]
Yes, I make sure of that but sometimes I get that error, that's why I suggested this issue

**Comment by Deivu** [comment]
I can consider this, but definitely will not ship in current 1.6.x, if considered, expect this to be on 2.x.x

**Comment by kaname-png** [comment]
Okay, thanks for adding this feature in the future that may be useful for others as well

**Comment by Deivu** [comment]
Check latest next-branch commits, new events on Shoukaku Class have been added, named `playerReady` and `playerDestroy`
