### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by iVatsuu** [Deivu/Shoukaku#41]
I am trying to play songs from Spotify but can't figure out how to go about implementing it. Can you please add Spotify support or give me some hints?

**Comment by Kyosodev** [comment]
You can't directly play from Spotify, search for the metadata (track name, author, album name, etc...) and then search that on YouTube and then play that instead

**Comment by Deivu** [comment]
Most of the libs that support Spotify just search the song, Lavalink itself **has no support to play Spotify songs**, hence its something you implement yourself, tho its doable with Shoukaku of course

**Comment by iVatsuu** [comment]
I thought Lavalink supported Spotify but anyways thanks for the info. I will figure out a way to do it.
