### ISSUE TITLE
Error Code 1011

### ISSUE THREAD

**Issue by AlphaDeveloper123** [Deivu/Shoukaku#44]
This error happens whenever I connect to the lavalink nodes. I don't really know what happens, but I used the same code as u did in the example.

**Comment by inhydrox** [comment]
Can you show your code and error with stack trace? Without I don't anyone will help

**Comment by xMercyTheDeveloper** [comment]
Yes I'm on my PC now lemme take a screenshot

**Comment by xMercyTheDeveloper** [comment]
![download](https://user-images.githubusercontent.com/42582303/120059173-6f2ff100-c058-11eb-8c02-c72728ffe0da.png)

**Comment by xMercyTheDeveloper** [comment]
It's just closing, then connecting again, then closing and etc

**Comment by xMercyTheDeveloper** [comment]
and my code is just the one from the README

**Comment by inhydrox** [comment]
Are you using shoukaku 1.5.x?

**Comment by inhydrox** [comment]
If version is below 1.5.x update it

**Comment by Deivu** [comment]
Fixed in 1.6.5
