### ISSUE TITLE
How to change region?

### ISSUE THREAD

**Issue by Nullelektron** [Deivu/Shoukaku#45]
Hello!
How to change a player region in shoukaku?
In eris-lavalink i see this option, but in shoukaku docs could not find.

**Comment by Kyosodev** [comment]
I'm not sure what you mean with player region, a player's "region" is determined by the location of the Lavalink Node. Would you mind linking this in the eris-lavalink documentation so I can understand what you mean?

**Comment by Nullelektron** [comment]
In nodes array:
```js
let nodes = [
    { host: 'localhost', port: 8080, region: 'eu', password: 'youshallnotpass' }
];
```
`region: 'eu'`

**Comment by inhydrox** [comment]
I think for that you'll have to marry shoukaku

**Comment by Deivu** [comment]
I'll usually just use group for grouping regions, as for how you would switch regions, well just supply it with an array of group, ex
`getNode(['eu'])`, this means shoukaku will load balance across the nodes in group eu
