### ISSUE TITLE
discord.js v13 support

### ISSUE THREAD

**Issue by danbulant** [Deivu/Shoukaku#49]
Discord.js master branch specifies the version `13` with few breaking APIs changed

**Comment by Deivu** [comment]
I haven't really kept up with discord.js master branch this last month, could you show a few of this breaking apis?

**Comment by danbulant** [comment]
actually that was my bad, I'm sorry for raising the issue. It's just because I'm trying to use discord v13 without dev lavalink, so I had to use older shoukaku as hinted in README.
