### ISSUE TITLE
IS shoukaku support discord.js v13

### ISSUE THREAD

**Issue by parasop** [Deivu/Shoukaku#50]
I Tried v13 but just track loaded but not playing

**Comment by hydrox19** [comment]
Shoukaku doesn't support the latest version of discord.js@dev but it does support before some breaking changes were introduced like the renaming stuff, so you can lock to the old commits and use.

**Comment by Deivu** [comment]
@parasop I tried the `next` branch with v13 and it works fine

**Comment by parasop** [comment]
> @parasop I tried the `next` branch with v13 and it works fine

![image](https://user-images.githubusercontent.com/63485824/127871530-366fe1f4-2c64-4d94-b3b6-23e614c810ba.png)

**Comment by Deivu** [comment]
@parasop  you need to install the next branch by uninstalling your current shoukaku version, then following the installation instructions in 
https://github.com/Deivu/Shoukaku/blob/next/README.md

**Comment by parasop** [comment]
> @parasop you need to install the next branch by uninstalling your current shoukaku version, then following the installation instructions in
> https://github.com/Deivu/Shoukaku/blob/next/README.md

![image](https://user-images.githubusercontent.com/63485824/127872673-f78081d6-94e1-4b2c-b57d-78f787b1e243.png)

**Comment by Deivu** [comment]
There are breaking changes on v2.0.0 aka next, one change is what you pass on the constructor of Shoukaku.
v2.0.0 introduces the ability to be used on almost any discord libraries in JS

Example if you use Discord.JS
```js
const { Shoukaku, Libraries } = require('shoukaku');

const lavalink = new Shoukaku(new Libraries.DiscordJS(client), LavalinkServers, ShoukakuOptions);
```

For the list of supported libraries, you can take a look in https://github.com/Deivu/Shoukaku/tree/next/src/libraries

**Comment by kakarot-dev** [comment]
Dosent that mean shoukaku cant support libraries other than djs and eris ?

**Comment by Deivu** [comment]
> Introduces the ability to be used on almost any discord libraries in JS

@kakarot-dev you got it the other way round, I made it so you can use other libraries with Shoukaku, it's just we coded one for Discord.JS and Eris, there is a README file in `https://github.com/Deivu/Shoukaku/tree/next/src/libraries` for more info about that

**Comment by kakarot-dev** [comment]
Ohh Kk sorry for the misunderstanding
