### ISSUE TITLE
Typings issue

### ISSUE THREAD

**Issue by kakarot-dev** [Deivu/Shoukaku#62]
https://github.com/Deivu/Shoukaku/blob/master/types/Shoukaku.d.ts#L1
this line depends on discord.js which is not really compatible with eris ( if im correct )
shouldnt this just be changed to
 ```
`${bigint}`
```

**Comment by Deivu** [comment]
Eris do have it on `string`

**Comment by kakarot-dev** [comment]
but doesnt that require discord.js specefically to be installed?

**Comment by kakarot-dev** [comment]
instead of snowflake, couldnt we just write string instead?

**Comment by Deivu** [comment]
I do want it as string as well, though I'm not sure how TS on discord.js will react to it

**Comment by kakarot-dev** [comment]
k, ill try it and if it works ill just open a pr later
btw we can just do 
```
`${bigint}` | string
```

**Comment by kakarot-dev** [comment]
that means it can be a bigint or a string, well both are strings anyway xd

**Comment by kakarot-dev** [comment]
i'll keep this open incase if anyone else has a better idea

**Comment by Deivu** [comment]
Fixed in #63
