### ISSUE TITLE
1011 Error with latest lavalink

### ISSUE THREAD

**Issue by darshanhihoriya** [Deivu/Shoukaku#68]
os - macos
lavalink verison - 3.3.2.5

Issue I'm getting below error with latest lavallink on kongnou bot

![image](https://user-images.githubusercontent.com/64433067/137610209-9635ee50-27f9-4b58-88ed-1e46a3c8fdc4.png)

**Comment by Deivu** [comment]
![image](https://user-images.githubusercontent.com/36309350/137611073-3984bb44-2c0a-4ee1-98fc-23c6c3e655d8.png)
Use Dev Branch 
https://ci.fredboat.com/viewType.html?buildTypeId=Lavalink_Build&branch_Lavalink=refs%2Fheads%2Fdev&tab=buildTypeStatusDiv

**Comment by Deivu** [comment]
Stable lavalink has been updated, so this issue no longer exists
