### ISSUE TITLE
[Error] Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by chrisdiscordandmore** [Deivu/Shoukaku#7]
![grafik](https://user-images.githubusercontent.com/52389841/63216680-2f28a400-c139-11e9-8d65-25d6ec9d5cb6.png)

Always getting this error when trying to play music

**Comment by Deivu** [comment]
What is your Discord.js version, or commit

**Comment by chrisdiscordandmore** [comment]
i dont need it anymore but here the version 11.5.1

**Comment by Deivu** [comment]
This library is only for Discord.js v12.0.0 aka Master. This lib is not compatible with older d.js versions
