### ISSUE TITLE
 Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('6')

### ISSUE THREAD

**Issue by pauldb09** [Deivu/Shoukaku#78]
| Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('3')
0|Greenbot  |     at new NodeError (node:internal/errors:371:5)
0|Greenbot  |     at ShoukakuHandler.emit (node:events:379:17)
0|Greenbot  |     at ShoukakuSocket.<anonymous> (/home/ubuntu/bots/green/node_modules/shoukaku/src/Shoukaku.js:1:680)
0|Greenbot  |     at ShoukakuSocket.emit (node:events:390:28)
0|Greenbot  |     at Object.callback (/home/ubuntu/bots/green/node_modules/shoukaku/src/node/ShoukakuQueue.js:1:440)
0|Greenbot  |     at callback (node:internal/streams/writable:552:21)
0|Greenbot  |     at onwriteError (node:internal/streams/writable:415:3)
0|Greenbot  |     at processTicksAndRejections (node:internal/process/task_queues:85:21) {
0|Greenbot  |   code: 'ERR_UNHANDLED_ERROR',
0|Greenbot  |   context: '3'
0|Greenbot  | }

This error is happening after 20 hours only

**Comment by Deivu** [comment]
Probably fixed on v3. Also don't forget to add error listener on Shoukaku
