### ISSUE TITLE
[Error] this.client.guilds.get is undefined

### ISSUE THREAD

**Issue by cotwo0139** [Deivu/Shoukaku#8]
An error occurred after the discord.js update ([discord.js#bbdbc4cfa789383b3dbecf5e6b8401ea2dd998](https://github.com/discordjs/discord.js/commit/bdbc4cfa789383b7b3dbbbbf5e6b8401ea2dddd8)) such as the title.

**Comment by Deivu** [comment]
Try to install the latest commit of Shoukaku; `9605ca8d24cf87b2d28539c1fca648a29f3ec723` and see if that fixes this issue.

**Comment by cotwo0139** [comment]
Thanks, I used old shoukaku version, thanks for reply!
