### ISSUE TITLE
Improve The Documentation

### ISSUE THREAD

**Issue by TheRealShreyash** [Deivu/Shoukaku#83]
I just want to say that improve the documentation because its very difficult to read. Rest your decision :)

**Comment by takase1121** [comment]
> I just want to say that improve the documentation because its very difficult to read. Rest your decision :)

At least provide some constructive feedback, eg. which part of the docs are hard to read, what is wrong, etc.

**Comment by Deivu** [comment]
Would be nice to do so, but for now, my time is finite. Probably planned some time in future

**Comment by TheRealShreyash** [comment]
> constructive feedback, eg. which part of the docs are hard to read, what is wrong, et

Sorry if you got hurt you took it wrong way

**Comment by TheRealShreyash** [comment]
> Would be nice to do so, but for now, my time is finite. Probably planned some time in future

I see man

**Comment by Deivu** [comment]
PRs are always welcome if you think you want to update some of the documented things on docs
