### ISSUE TITLE
Shoukaku not reconnect correctly on this node error

### ISSUE THREAD

**Issue by flav28** [Deivu/Shoukaku#84]
![IMG_20220508_041415](https://user-images.githubusercontent.com/48295189/167279127-6218ba5c-6ab1-4268-996a-b2cc588f1c23.jpg)

**Comment by 0t4u** [comment]
ECONNRESET is a TCP connection error to your Lavalink server. This has nothing to do with Shoukaku, as it is a networking error. For ways to debug this error, please see the StackOverflow answer below.
https://stackoverflow.com/a/17637900
