### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by AJ-OP2311** [Deivu/Shoukaku#99]
![unknown](https://user-images.githubusercontent.com/95399901/185434560-3f32c270-9bd5-4193-809a-3c7a312f19a1.png)
When am playing song show this issue. Please help

**Comment by wxifuwu** [comment]
Any updates on this? Running into the same issue on MacOS 12.3.1 | Node v18.7. Haven't tried any other OS yet

**Comment by AJ-OP2311** [comment]
> Any updates on this? Running into the same issue on MacOS 12.3.1 | Node v18.7. Haven't tried any other OS yet

It's Issue In Node Version

**Comment by rajamoulimallareddy** [comment]
> Any updates on this? Running into the same issue on MacOS 12.3.1 | Node v18.7. Haven't tried any other OS yet

Use node version 17 cause node v18 isn't working

**Comment by AJ-OP2311** [comment]
Its Solve
